<form action='<?php echo base_url();?>user/password' method='post' name='password'>
    <input type="hidden" name="redirect" value="<?php $redirect; ?>" />   
    
        <h2>Reset Password</h2>
        
        <ul>
            <li>
                <label for='old_pass'>Old Password</label>
                <input type='password' name='old_pass' />
            </li>
            <li>
                <label for='new_pass'>New Password</label>
                <input type='password' name='new_pass' />
            </li>
            <li>
                <label for='confirm_pass'>Confirm New Password</label>
                <input type='password' name='confirm_pass' />
            </li>
        </ul> 

    <input type='Submit' value='Login' />            
</form>